on:
  push:
    branches:
      - last





jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: "login to docker"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.TOKEN}}
      - name: "Build docker image"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/soft2 .
      - name: "Pushing to docker"
        run: docker push ${{secrets.DOCKER_USERNAME}}/soft2 

